AddEvent("OnPackageStart", function () 
    local Weapon = GetWeaponIdentifier():NewWeapon(22)
	Weapon:SetWeaponType(1)
	Weapon:SetWeaponSubType(1)
	Weapon:SetWeaponModel(USkeletalMesh.LoadFromAsset("/Game/Weapons/Meshes/Pistol04/SK_Pistol04"))
	Weapon:SetStaticWeaponModel(UStaticMesh.LoadFromAsset("/Game/Weapons/Meshes/Pistol04/SM_Pistol04"))
	Weapon:SetMeshScale(FVector(1.000000, 1.000000, 1.000000))
	Weapon:SetEquipTime(0.23)
	Weapon:SetUnequipTime(0.45)
	Weapon:SetAimWalkSpeed(170.0)
	Weapon:SetCameraAimTargetOffset(FVector(170.000000, 65.000000, 14.000000))
	Weapon:SetCameraAimFoV(65.0)
	Weapon:SetAimBlendTime(0.35)
	Weapon:SetRange(7000.0)
	Weapon:SetRecoil(0.2)
	Weapon:SetCameraShake(1.0)
	Weapon:SetCameraShakeCrouching(0.5)
	Weapon:SetSpreadMin(0.1)
	Weapon:SetSpreadMax(2.0)
	Weapon:SetSpreadMovementModifier(0.2)
	Weapon:SetSpreadCrouchingModifier(-0.3)
	Weapon:SetRateOfFire(100.0)
	Weapon:SetMagazineModel(UStaticMesh.LoadFromAsset("/Game/Weapons/Meshes/Pistol04/SK_Pistol04_Mag"))
	Weapon:SetMagazineSize(9)
	Weapon:SetMagazineDropTime(0.32)
	Weapon:SetScope(false)
	Weapon:SetShotSound(USoundCue.LoadFromAsset("/Game/Weapons/Sounds/Cues/HZPistol01_Cue"))
	Weapon:SetShotAnimation(UAnimSequence.LoadFromAsset("/Game/Weapons/Animations/A_Pistol04_Fire"))
	Weapon:SetShotAnimationTime(0.3)
	Weapon:SetMuzzleFlash(UParticleSystem.LoadFromAsset("/Game/Weapons/VFX/Particles/Weapons/PS_DesertEagle"))
	Weapon:SetShellDelay(0.0)
	Weapon:SetProjectileShell(UParticleSystem.LoadFromAsset("/Game/Weapons/VFX/Particles/Shells/P_Shell"))
	Weapon:SetShellSmoke(UParticleSystem.LoadFromAsset("/Game/Weapons/VFX/Impacts/Particles/P_ShellSmoke"))
	Weapon:SetAttachmentLocationModifier(FVector(-8.000000, 3.700000, 0.850000))
	Weapon:SetAttachmentRotationModifier(FRotator(10.565318, 86.711197, 10.886045))
	Weapon:SetReloadAnimation(UAnimSequence.LoadFromAsset("/Game/Weapons/Animations/A_Pistol04_Reload"))
	Weapon:SetReloadAnimationTime(0.96)
	Weapon:SetCharacterReloadAnimation(UAnimSequence.LoadFromAsset("/Game/Character/Animations/Handgun/A_HG_Reload"))
	Weapon:SetLeftHandIKLocation(FVector(-2.000000, 8.000000, -5.000000))
	Weapon:SetLeftHandARIdleIKLocation(FVector(0.000000, 0.000000, 0.000000))
	Weapon:SetLeftHandARIdleIKLocationCrouching(FVector(0.000000, 0.000000, 0.000000))
	Weapon:SetHUDImage(UTexture2D.LoadFromAsset("/Game/Weapons/Images/T_Pistol04"))
	Weapon:SetAllowAimWhileCrouching(true)
	Weapon:SetZoomInSound(nil)
	Weapon:SetZoomOutSound(nil)
	Weapon:SetEquipSound(USoundCue.LoadFromAsset("/Game/Character/Sounds/Holster/Equip_Fabric_1_A_Cue"))
	Weapon:SetUnequipSound(USoundCue.LoadFromAsset("/Game/Character/Sounds/Holster/UnEquip_Fabric_1_A_Cue1"))
	Weapon:SetReloadStartSound(USoundCue.LoadFromAsset("/Game/Weapons/Sounds/Cues/HZRemoveMag_Cue"))
	Weapon:SetReloadEndSound(USoundCue.LoadFromAsset("/Game/Weapons/Sounds/Cues/HZInsertMag_Cue"))
	Weapon:SetNoAmmoSound(USoundCue.LoadFromAsset("/Game/Weapons/Sounds/Cues/HZEmptyMag_Cue"))
	GetWeaponIdentifier():RegisterWeapon(Weapon)
end)